@LICENSE@
// This file has been generated by the metapod robotbuilder library.

#ifdef _MSC_VER
# pragma warning( push )
// The following warnings are only needed if the FloatType is float, because
// the code generator uses double anyway.
// disable warning C4305 truncation from 'double' to 'float'
// disable warning C4244 conversion from 'double' to 'float', possible loss of data
# pragma warning( disable: 4305 4244)
#endif

#include "@ROBOT_NAME@.hh"

namespace metapod {

  @init_nodes@


  template <> Spatial::InertiaTpl<FloatType> @ROBOT_CLASS_NAME@<FloatType>::inertias[@node_id@] = {
    @init_inertias@};

  template <> @ROBOT_CLASS_NAME@<FloatType>::VectorNBDOFi @ROBOT_CLASS_NAME@<FloatType>::fdNodesFirst = @ROBOT_CLASS_NAME@<FloatType>::VectorNBDOFi::Zero();
  template <> @ROBOT_CLASS_NAME@<FloatType>::VectorNbFdDOFi @ROBOT_CLASS_NAME@<FloatType>::fdNodes = @ROBOT_CLASS_NAME@<FloatType>::VectorNbFdDOFi::Zero();
  template <> @ROBOT_CLASS_NAME@<FloatType>::VectorNbIdDOFi @ROBOT_CLASS_NAME@<FloatType>::idNodes = @ROBOT_CLASS_NAME@<FloatType>::VectorNbIdDOFi::Zero();
  template <> @ROBOT_CLASS_NAME@<FloatType>::TranspositionsNBDOFi @ROBOT_CLASS_NAME@<FloatType>::Q = @ROBOT_CLASS_NAME@<FloatType>::TranspositionsNBDOFi(@ROBOT_CLASS_NAME@<FloatType>::NBDOF);
  template <> @ROBOT_CLASS_NAME@<FloatType>::TranspositionsNbFdDOFi @ROBOT_CLASS_NAME@<FloatType>::Q1 = @ROBOT_CLASS_NAME@<FloatType>::TranspositionsNbFdDOFi(@ROBOT_CLASS_NAME@<FloatType>::nbFdDOF);
  template <> int @ROBOT_CLASS_NAME@<FloatType>::fdNodesFillIndex = 0;
  template <> int @ROBOT_CLASS_NAME@<FloatType>::idNodesFillIndex = 0;
}

#ifdef _MSC_VER
# pragma warning( pop )
#endif
